### ISSUE TITLE
The mouse returns to the (0,0) after using MouseTo.setTarget(x,y)

### ISSUE THREAD

**Issue by maplemikey** [per1234/MouseTo#2] opened 2018-08-22 04:15 UTC
whenever void loop() runs; the coordination of the mouse get returns to the (0,0).
For example, when I made my mouse move to (100,100) with delay of 1000ms,
it gets backward and forward between (0,0) and (100,100) every seconds.

I have to make it stay in the set position, but I cannot make it right.
How Can I Solve It? We're very running out of time TT;;;;

**Comment by per1234** [comment] 2018-08-22 04:55
It's not clear to me what you're saying but it sounds like the correct and expected behavior. The way this library achieves absolute positioning is by first "homing" the mouse pointer to the 0,0 coordinates, then moving to the target coordinates. That is necessary because the code has no way of knowing where on the screen the mouse pointer happens to be. It is possible to disable this homing via the optional `homeFirst` parameter of [`MouseTo.setTarget()`](https://github.com/per1234/MouseTo#mousetosettargettargetx-targety-homefirst) but you should note that if the physical mouse is used to move the mouse pointer the library doesn't have any way to know that and so all positioning will be off until it is homed again.

I'm going to go ahead and close this but I'll be happy to reopen if you can provide a complete minimal sketch that demonstrates a bug. If you only want help using the library I'm happy to do what I can but I ask that we have that discussion on the [Arduino Forum](http://forum.arduino.cc/).

**Closed as completed by per1234** 2018-08-22 04:55 UTC
